#!/system/bin/sh

#########################################################
#
#  My script to set SE-linux to permissive on the fly.
#  Coded by:  clnelson@github.com
#  Email:     dumb.droid.dev@gmail.com
#  Created:   Sep-2020
#
#########################################################

Get=$(sudo getenforce)
Per=Permissive

echo -e "${yel}A script to set ${bred}SElinux ${res}${yel}to ${bgrn}permissive${res}\n"

echo -e "Your system is currently set to: ${bred}${Get}\n"
if echo  $Get | grep -q $Per;
then
	echo -e "${yel}System already set to: ${grn}$Per\n"
      exit 1
else #[ ${Get} -eq ${Per} ]
	echo -e "${cya}Setting new permissions...\n"
      sudo setenforce 0
	echo -e "${blu}Security profile has changed to: ${bgrn}$(sudo getenforce)\n"
fi
