#!/usr/bin/env bash

## Git configuration variables for my system
git config --global credential.helper "cache --timeout=7200"
git config --global core.editor "nano"
git congig --global branch.autoSetupRebase "remote"
git config --global color.branch "always"
git config --global color.diff "always"
git config --global diff.colorMoved "true"
git config --global color.diff.plain "bold white"
git config --global color.diff.meta "magenta"
git config --global color.diff.frag "bold yellow"
git config --global color.diff.old "red"
git config --global color.diff.new "green"
git config --global color.diff.commit "bold green"
git config --global color.diff.whitespace "red"
git config --global color.diff.oldMoved "red"
git config --global color.diff.newMoved "green"
git config --global color.diff.oldMovedDimmed "bold white"
git config --global color.diff.oldMovedAlternative "bold yellow"
git config --global color.diff.oldMovedAlternativeDimmed "bold green"
git config --global color.diff.newMovedDimmed "green"
git config --global color.diff.newMovedAlternative "blue"
git config --global color.diff.newMovedAlternativeDimmed "magenta"
git config --global color.decorate.branch "cyan"
git config --global color.decorate.remoteBranch "red"
git config --global color.decorate.tag "green"
git config --global color.decorate.stash "yellow"
git config --global color.decorate.HEAD "white"
git config --global color.grep "always"
git config --global color.grep.context "bold red"
git config --global color.grep.filename "yellow"
git config --global color.grep.function "white"
git config --global color.grep.linenumber "bold cyan"
git config --global color.grep.match "bold green"
git config --global color.grep.matchContext "bold green"
git config --global color.grep.matchSelected "bold green"
git config --global color.grep.selected "bold black"
git config --global color.grep.separator "bold yellow"
git config --global color.interactive "always"
git config --global color.interactive.prompt "bold white"
get config --global color.interactive.header "yellow"
get config --global color.interactive.help "bold magenta"
get config --global color.interactive.error "bold red"
get config --global color.pager "enable"
get config --global color.showBranch "always"
get config --global color.status "always"
get config --global color.status.header "bold white"
get config --global color.status.added "green"
get config --global color.status.changed "yellow"
get config --global color.status.untracked "bold black"
get config --global color.status.branch "cyan"
get config --global color.status.nobranch "red"
get config --global color.status.localBranch "white"
get config --global color.status.remoteBranch "red"
get config --global color.status.unmerged "magenta"
get config --global color.ui "always"
get config --global column.ui "always"
get config --global column.status "always"
get config --global column.tag "always"
get config --global diff.algorithm "minimal"
get config --global fetch.prune "true"
get config --global fetch.output "compact"
get config --global format.pretty "always"
get config --global help.format "web"
get config --global help.browser "firefox"
get config --global merge.conflictStyle "diff3"
get config --global merge.log "true"
get config --global merge.tool "bc"
get config --global rebase.stat "true"
get config --global rebase.autoStash "true"
get config --global rerere.autoUpdate "true"
git config --global rerere.enabled "true"
