steps:
  - task: UseDotNet@2
    displayName: Use .NET SDK 5.0.203
    inputs:
      packageType: sdk
      version: 5.0.203

  - task: DotNetCoreCLI@2
    displayName: Compile common code
    inputs:
      command: build
      projects: 'Git-Credential-Manager.sln'
      arguments: '--configuration=Linux$(configuration)'

  - task: DotNetCoreCLI@2
    displayName: Run common unit tests
    inputs:
      command: test
      projects: 'Git-Credential-Manager.sln'
      arguments: '--configuration=Linux$(configuration)'
      publishTestResults: true
      testRunTitle: 'Unit tests (Linux)'
