## An alias file for quicker syntax of common commands

## System level aliases
alias shit='inxi'
alias shitty='sudo inxi'
alias sumod6='sudo chmod 644'
alias sumod7='sudo chmod 755'
alias suown="sudo chown $USER:$USER"
alias diff='diff --color=always'
alias diffy='diff -yw --suppress-common-lines'
alias bat='bat --color=always --wrap=character --terminal-width=-5 --italic-text=always --style=full --theme=Solarized\ \(light\)'
alias c='bat'
alias cn='cat -nst'
alias back="tac -r -s 'x\|[^x]' " # Reverse file and lines
alias cpr='cp -ir'
alias file='file -s -z'
alias ifile='file -s -z -i'
alias fhere='find . -name '
alias cls='clear'
alias mkd='mkdir -pv'
alias ..='cd ..'
alias lesser='less -R --status-column --quit-if-one-screen --quit-on-intr --no-lessopen --squeeze-blank-lines --hilite-unread'
alias path='echo ${PATH}'
alias top='htop'
alias du='ncdu'
alias df='df -Tha --total'
alias free='free -mth'
alias ps='ps auxf'
alias psg="ps aux | grep -v grep | grep -i -e VSZ -e"
alias wg='wget2'
alias wget2='wget2 -c --progress=bar'
alias histg='history | grep'
alias rc="nano $HOME/.bashrc"
alias aliases="nano $HOME/.bash_aliases"
alias src="source ~/.bashrc"
alias net='curl ipinfo.io/ip'
alias xx='exit'
alias pff='poweroff'
alias setperf='echo "performance" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor'
alias setsave='echo "powersave" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor'
alias rfkill='sudo rfkill --output DEVICE,ID,TYPE,TYPE-DESC,SOFT,HARD'
alias ip='ip -c -h -d -s -s'

## File removal "securely" for the noid...
alias sub='scrub -SRfr -p pfitzner33'
alias susub='sudo scrub -SRfr -p pfitzner33'
alias bish='scrub -SRfr -p pfitzner33 ~/.bash_history ~/.lesshst'
alias shard='shred -fzn 23 --remove=wipe'
alias sushard='sudo shred -fzn 23 --remove=wipe'
alias rmf='rm -rf'
alias surm='sudo rm -rf'

## Aliases for package management
alias ag='sudo apt-get'
alias ai='sudo apt-get install'
alias ap='sudo apt-get purge'
alias al='apt list'
alias ali='apt list --installed'
alias alig='apt list --installed | grep'
alias as='apt search'
alias aptsh='apt show'
alias au='sudo apt-get update'
alias auu='sudo apt-get update && sudo apt-get upgrade'
alias clapt='sudo apt autoremove && sudo apt remove && sudo apt autoclean && sudo apt clean'

## Dpkg simplification
alias lintian='lintian --color=always'
alias dp='sudo dpkg'
alias dp.h='dpkg --help'
alias dp.fh='dpkg --force-help'
alias dp.i='sudo dpkg -i'
alias dp.l='sudo dpkg -l'
alias dp.lg='sudo dpkg -l | grep'
alias dp.L='sudo dpkg -L'
alias dp.s='sudo dpkg -S'
alias dp.ca='sudo dpkg --configure -a'

## Android development commands 
alias adb_='adb devices -l'
alias adb.rb='adb reboot bootloader'
alias adb.rr='adb reboot recovery'
alias adbk='adb kill-server'
alias adb.pu='adb push'
alias adb.ll='adb pull'
alias adb.sh='adb shell'

alias fast='fastboot'
alias fast_='fastboot devices -l'
alias fast.re='fastboot reboot'
alias fast.rb='fastboot reboot bootloader'
alias fast.fr='fastboot flash recovery'
alias fast.fb='fastboot flash boot'
alias fast.o='fastboot oem'
alias fast.var='fastboot getvar all'

## Repo aliases for remote repositories
alias repoh='repo help --all'
alias rerepo='repo rebase -i'
alias rebaser='repo rebase --autosquash --auto-stash -m'
alias repair='repo sync --detach --no-clone-bundle --force-remove-dirty --force-sync -j4'
alias respo='repo sync --current-branch --no-tags --no-clone-bundle --optimized-fetch -j2'
alias rechk='repo checkout --branch'
alias reup='repo selfupdate'
alias repin='repo init --no-clone-bundle --no-tags --current-branch --reference="/home/tux/Android/mirror" --dissociate --platform=linux -u'
alias repoir='repo sync --no-clone-bundle --force-sync --optimized-fetch -j2' # For my mirror repos to include tags and branches
alias rstat='repo status'
alias rediff='repo diffmanifests'
alias reman='repo manifest'

## Git for lazy people
alias git='hub'
alias git.h='git help'
alias git.ha='git help -a'
alias git.bra='git branch --list -a --color=always'
alias regit='git rebase -i'
alias git.rbc='git rebase --continue'
alias git.rba='git rebase --abort'
alias git.rbs='git rebase --skip'
alias git.chk='git checkout'
alias git.cl='git clone'
alias gstat='git status'
alias gadd='git add . '
alias git.c='git commit -m'
alias git.ca='git commit --amend -m'
alias git.cn='git commit --no-edit -m'
alias git.pu='git push'
alias git.ll='git pull'
alias git.re='git reset --hard'
alias git.add='git remote add'
alias git.set='git remote --set-upstream'


#alias perry='clone git@github.com:MotorolaMobilityLLC/kernel-msm.git -b nougat-7.1.1-release-perry'
#alias surf='clone git@github.com:MotorolaMobilityLLC/kernel-msm.git -b pie-9.0.0-release-pcb29'
