name: GCM-Core

on:
  workflow_dispatch:
  push:
    branches: [ main, linux ]
  pull_request:
    branches: [ main, linux ]

jobs:
  validate_gcm:
    name: "CI"

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, windows-2019, macos-10.15]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Indicate full history so Nerdbank.GitVersioning works.

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.103

    - name: Install dependencies
      run: dotnet restore

    - name: Build Windows
      if: contains(matrix.os, 'windows')
      run: dotnet build --configuration WindowsRelease

    - name: Build Linux
      if: contains(matrix.os, 'ubuntu')
      run: dotnet build --configuration LinuxRelease

    - name: Build macOS
      if: contains(matrix.os, 'macos')
      run: dotnet build --configuration MacRelease

    - name: Test
      run: dotnet test --no-restore --verbosity normal
