name: "release-winget"
on:
  release:
    types: [released]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - id: update-winget
      name: Update winget repository
      uses: mjcheetham/update-winget@v1.2.2
      with:
        id: Microsoft.GitCredentialManagerCore
        token: ${{ secrets.WINGET_TOKEN }}   
        releaseAsset: gcmcore-win-x86-(.*)\.exe
        manifestText: |
          PackageIdentifier: {{id}}
          PackageVersion: {{version}}
          PackageName: Git Credential Manager Core
          Publisher: Microsoft Corporation
          Moniker: git-credential-manager-core
          PackageUrl: https://aka.ms/gcmcore
          Tags:
          - gcm
          - gcmcore
          - git
          - credential 
          License: Copyright (C) Microsoft Corporation
          ShortDescription: Secure, cross-platform Git credential storage with authentication to GitHub, Azure Repos, and other popular Git hosting services.
          Installers:
          - Architecture: x86
            InstallerUrl: {{url}}
            InstallerType: inno
            InstallerSha256: {{sha256}}
          PackageLocale: en-US
          ManifestType: singleton
          ManifestVersion: 1.0.0
        alwaysUsePullRequest: true
