## An alias file for quicker syntax of common commands

## System level aliases
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias xx='exit'
alias shit='sudo inxi'
alias mod6='chmod 644'
alias mod7='chmod 755'
alias own="chown $(whoami):$(whoami)"
alias diff='diff --color=always'
alias diffy='diff -yw --suppress-common-lines'
alias c='bat'
alias cn='cat -nst'
alias back="tac -r -s 'x\|[^x]' " # Reverse file and lines
alias cp='cp -ir'
alias mv='mv -i'
alias file='file -s -z'
alias fhere='find . -name '
alias cls='clear'
alias mkd='mkdir -pv'
alias path='echo ${PATH}'
alias top='htop'
alias du='du -h'
alias df='df -Tha --total'
alias free='free -mth'
alias psa='ps auxf'
alias wg='wget2'
alias wget2='wget2 -c --progress=bar'
alias histg='history | grep'
alias rc="nano $HOME/.bashrc"
alias funcs="nano -Y sh $HOME/.bash_functions"
alias aliases="nano -Y sh $HOME/.bash_aliases"
alias src="source ~/.bashrc"
alias net='curl ipinfo.io'
alias ip='ip -c -h -d -s -s a'
alias setperf='echo "performance" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor'
alias setsave='echo "powersave" | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor'
alias rfkill='sudo rfkill --output DEVICE,ID,TYPE,TYPE-DESC,SOFT,HARD'

## File removal "securely" for the noid...
alias sub='scrub -SRfr -p pfitzner33'
alias susub='sudo scrub -SRfr -p pfitzner33'
alias bish='scrub -SRfr -p pfitzner33 ~/.bash_history ~/.lesshst'
alias shard='shred -fzn 23 --remove=wipe'
alias sushard='sudo shred -fzn 23 --remove=wipe'
alias rmf='rm -rf'
alias surf='sudo rm -rf'

## Aliases for package management
alias ag='apt-get'
alias ai='apt-get install'
alias ap='apt-get purge'
alias al='apt list'
alias ali='apt list --installed'
alias alig='apt list --installed | grep'
alias as='apt search'
alias aptsh='apt show'
alias au='apt-get update'
alias auu='apt-get update && apt-get upgrade'
alias clapt='apt autoremove && apt remove && apt autoclean && apt clean'

## Dpkg simplification
alias dp='dpkg'
alias dp.h='dpkg --help'
alias dp.fh='dpkg --force-help'
alias dp.i='dpkg -i'
alias dp.l='dpkg -l'
alias dp.lg='dpkg -l | grep'
alias dp.L='dpkg -L'
alias dp.s='dpkg -S'
alias dp.con='dpkg --configure -a'

## Android development commands
alias adb_='sudo adb devices -l'
alias adbk='sudo adb kill-server'
alias adb.pu='sudo adb push'
alias adb.ll='sudo adb pull'
alias adb.sh='sudo adb shell'
alias adb.rb='sudo adb reboot bootloader'
alias adb.rr='sudo adb reboot recovery'

alias fast='sudo fastboot'
alias fast_='sudo fastboot devices -l'
alias fast.re='sudo fastboot reboot'
alias fast.rb='sudo fastboot reboot bootloader'
alias fast.fr='sudo fastboot flash recovery'
alias fast.fb='sudo fastboot flash boot'
alias fast.o='sudo fastboot oem'
alias fast.var='sudo fastboot getvar all'

## Git for lazy people
alias git.h='git help'
alias git.ha='git help -a'
alias git.bra='git branch --list -a --color=always'
alias regit='git rebase -i'
alias git.rbc='git rebase --continue'
alias git.rba='git rebase --abort'
alias git.rbs='git rebase --skip'
alias git.chk='git checkout'
alias git.cl='git clone'
alias gstat='git status'
alias gadd='git add . '
alias git.l='git log'
alias git.c='git commit -m'
alias git.ca='git commit --amend -m'
alias git.cn='git commit --no-edit -m'
alias git.pu='git push'
alias git.ll='git pull'
alias git.re='git reset --hard'
alias git.add='git remote add'
alias git.set='git remote --set-upstream'
alias git.re='git reset'
alias git.rh='git reset --hard'
alias git.rs='git reset --soft'
alias git.cp='git cherry-pick'
alias git.st='git stash'
alias git.sq='git squash'
