steps:
  - script: src/osx/Installer.Mac/layout.sh --configuration='$(configuration)' --output='$(Build.StagingDirectory)/payload' --symbol-output='$(Build.StagingDirectory)/symbols'
    displayName: Layout installer payload

  - task: PublishPipelineArtifact@0
    displayName: Upload unsigned payload
    inputs:
      artifactName: 'tmp.macpayload_unsigned' 
      targetPath: '$(Build.StagingDirectory)/payload'

  - task: PublishPipelineArtifact@0
    displayName: Upload symbols
    inputs:
      artifactName: 'tmp.macsymbols'
      targetPath: '$(Build.StagingDirectory)/symbols'
